# Generated by Django 5.2.4 on 2025-09-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('english', 'English'), ('hindi', 'Hindi'), ('other', 'Other')], default='english', max_length=20),
        ),
    ]
