# Generated by Django 5.2.4 on 2025-09-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pincode',
        ),
        migrations.AddField(
            model_name='profile',
            name='child_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='experience',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='qualification',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='relation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('english', 'English'), ('hindi', 'Hindi'), ('odia', 'Odia'), ('malayalam', 'Malayalam'), ('tamil', 'Tamil'), ('gujarati', 'Gujarati'), ('marathi', 'Marathi'), ('telugu', 'Telugu'), ('bengali', 'Bengali'), ('punjabi', 'Punjabi'), ('kannada', 'Kannada'), ('urdu', 'Urdu'), ('other', 'Other')], default='english', max_length=20),
        ),
    ]
