# Generated by Django 5.2.4 on 2025-09-11 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profile_address_remove_profile_mobile_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='board',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='child_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='relation',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='roll_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='school_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='student_class',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='subject',
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='student', max_length=20)),
                ('unique_name', models.CharField(max_length=100, unique=True)),
                ('father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('roll_number', models.CharField(blank=True, max_length=50, null=True)),
                ('school_name', models.CharField(blank=True, max_length=100, null=True)),
                ('board', models.CharField(blank=True, choices=[('UP BOARD', 'UP BOARD'), ('CBSE BOARD', 'CBSE BOARD'), ('ICSE BOARD', 'ICSE BOARD'), ('MAHARASHTRA BOARD', 'MAHARASHTRA BOARD'), ('ODISHA BOARD', 'ODISHA BOARD')], max_length=50, null=True)),
                ('student_class', models.CharField(blank=True, choices=[('6', 'Class 6'), ('7', 'Class 7'), ('8', 'Class 8'), ('9', 'Class 9'), ('10', 'Class 10'), ('11', 'Class 11'), ('12', 'Class 12')], max_length=10, null=True)),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('qualification', models.CharField(blank=True, max_length=200, null=True)),
                ('experience', models.CharField(blank=True, max_length=50, null=True)),
                ('child_name', models.CharField(blank=True, max_length=150, null=True)),
                ('relation', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'unique_name')},
            },
        ),
    ]
