# Generated by Django 5.2.4 on 2025-09-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_unique_together_remove_profile_board_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='student_name',
            field=models.CharField(default='logout', max_length=150),
            preserve_default=False,
        ),
    ]
