# Generated by Django 5.2.4 on 2025-09-12 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_studentprofile_student_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='role',
        ),
    ]
