# Generated by Django 5.2.4 on 2025-09-14 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_studentprofile_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='unique_name',
            new_name='username',
        ),
        migrations.AlterUniqueTogether(
            name='studentprofile',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='language',
            field=models.CharField(choices=[('english', 'English'), ('hindi', 'Hindi'), ('odia', 'Odia'), ('marathi', 'Marathi'), ('gujarati', 'Gujarati'), ('punjabi', 'Punjabi'), ('telugu', 'Telugu'), ('bengali', 'Bengali'), ('kannada', 'Kannada'), ('urdu', 'Urdu'), ('other', 'Other')], default='english', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='student_picture',
            field=models.ImageField(blank=True, null=True, upload_to='students/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('english', 'English'), ('hindi', 'Hindi'), ('odia', 'Odia'), ('marathi', 'Marathi'), ('gujarati', 'Gujarati'), ('punjabi', 'Punjabi'), ('telugu', 'Telugu'), ('bengali', 'Bengali'), ('kannada', 'Kannada'), ('urdu', 'Urdu'), ('other', 'Other')], default='english', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='unique_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='address',
            field=models.CharField(default='Not Provided', max_length=255),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='board',
            field=models.CharField(choices=[('UP BOARD', 'UP BOARD'), ('CBSE BOARD', 'CBSE BOARD'), ('ICSE BOARD', 'ICSE BOARD'), ('MAHARASHTRA BOARD', 'MAHARASHTRA BOARD'), ('ODISHA BOARD', 'ODISHA BOARD')], default='CBSE BOARD', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='father_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='mobile_number',
            field=models.CharField(default='N/A', max_length=15),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='pincode',
            field=models.CharField(default='000000', max_length=10),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='roll_number',
            field=models.CharField(default='N/A', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='school_name',
            field=models.CharField(default='N/A', max_length=150),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='student_class',
            field=models.CharField(choices=[('6', 'Class 6'), ('7', 'Class 7'), ('8', 'Class 8'), ('9', 'Class 9'), ('10', 'Class 10'), ('11', 'Class 11'), ('12', 'Class 12')], default='6', max_length=10),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='subject',
            field=models.CharField(default='General', max_length=200),
        ),
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=150)),
                ('address', models.TextField(default='Not Provided')),
                ('pincode', models.CharField(default='000000', max_length=10)),
                ('mobile_number', models.CharField(default='N/A', max_length=15)),
                ('relation', models.CharField(default='Parent', max_length=50)),
                ('student_class', models.CharField(choices=[('6', 'Class 6'), ('7', 'Class 7'), ('8', 'Class 8'), ('9', 'Class 9'), ('10', 'Class 10'), ('11', 'Class 11'), ('12', 'Class 12')], default='6', max_length=10)),
                ('child_name', models.CharField(default='Unknown', max_length=150)),
                ('child_roll_number', models.CharField(default='N/A', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=150)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('address', models.TextField(default='Not Provided')),
                ('pincode', models.CharField(default='000000', max_length=10)),
                ('qualification', models.CharField(default='Not Provided', max_length=200)),
                ('subject', models.CharField(default='General', max_length=100)),
                ('language', models.CharField(choices=[('english', 'English'), ('hindi', 'Hindi'), ('odia', 'Odia'), ('marathi', 'Marathi'), ('gujarati', 'Gujarati'), ('punjabi', 'Punjabi'), ('telugu', 'Telugu'), ('bengali', 'Bengali'), ('kannada', 'Kannada'), ('urdu', 'Urdu'), ('other', 'Other')], default='english', max_length=20)),
                ('mobile_number', models.CharField(default='N/A', max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='child_name',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='relation',
        ),
    ]
