# Generated by Django 5.2.4 on 2025-09-14 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_unique_name_studentprofile_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='unique_name',
        ),
    ]
