# Generated by Django 5.2.4 on 2025-09-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='student_picture',
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('student', 'Student')], max_length=10),
        ),
        migrations.DeleteModel(
            name='ParentProfile',
        ),
        migrations.DeleteModel(
            name='TeacherProfile',
        ),
    ]
